from flask_cors import CORS
from flask import Flask, request, jsonify
import threading
import os
import requests
import openai
import re
from dotenv import load_dotenv

load_dotenv()
app = Flask(__name__)
CORS(app)

SPOTIFY_USER_ID = os.getenv("SPOTIFY_USER_ID")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
openai.api_key = OPENAI_API_KEY

# 🔐 인증
def refresh_access_token():
    response = requests.post(
        "https://accounts.spotify.com/api/token",
        data={
            "grant_type": "refresh_token",
            "refresh_token": os.getenv("SPOTIFY_REFRESH_TOKEN"),
            "client_id": os.getenv("SPOTIFY_CLIENT_ID"),
            "client_secret": os.getenv("SPOTIFY_CLIENT_SECRET"),
        }
    )
    if response.status_code == 200:
        return response.json()["access_token"]
    raise Exception("❌ Access Token 갱신 실패: " + response.text)

def get_headers():
    token = refresh_access_token()
    return {"Authorization": f"Bearer {token}"}

# 🎵 GPT에게 질문
def ask_chatgpt_for_playlist(prompt):
    response = openai.chat.completions.create(
        model="gpt-4-turbo", # 3.5도 가능. 시연영상에서는 3.5사용
        messages=[
            {"role": "system", "content": "You're a music playlist assistant."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.7
    )
    return response.choices[0].message.content

# 🎧 Spotify 관련
def search_track_uri(track_name):
    url = "https://api.spotify.com/v1/search"
    headers = get_headers()
    params = {"q": track_name, "type": "track", "limit": 1}
    r = requests.get(url, headers=headers, params=params)
    items = r.json().get("tracks", {}).get("items", [])
    return items[0]["uri"] if items else None

def create_spotify_playlist(name, description="Generated by ChatGPT"):
    url = f"https://api.spotify.com/v1/users/{SPOTIFY_USER_ID}/playlists"
    headers = get_headers()
    body = {"name": name, "description": description, "public": False}
    r = requests.post(url, headers=headers, json=body)
    if r.status_code == 201:
        return r.json()["id"]
    raise Exception("❌ 플레이리스트 생성 실패!")

def add_tracks_to_playlist(playlist_id, uris):
    url = f"https://api.spotify.com/v1/playlists/{playlist_id}/tracks"
    headers = get_headers()
    r = requests.post(url, headers=headers, json={"uris": uris})
    return r.status_code == 201 or r.status_code == 200

# 📡 API 엔드포인트
@app.route("/generate_playlist", methods=["POST"]) # POST형식으로 받아옴
def generate_playlist():
    data = request.get_json()

    book_title = data.get("book_title", "") # 책 제목
    story = data.get("book_story") # 줄거리 (c++부분에서 if문 형태로 받아왔었음)


    print(f"📘 책 제목: {book_title}") # 프롬프트 확인용 출력
    print(f"📝 요약: {story}")

    prompt = (f"'{book_title}'이라는 책에 대해 알려줄게.\n"
    f"요약 줄거리:\n{story}\n\n"
    f"이 책의 배경과 내용을 바탕으로 어울리는 노래 5곡을 추천해줘.")
    playlist_name = f"{book_title} 플레이리스트"

    # GPT로 노래 추천받기
    songs = ask_chatgpt_for_playlist(prompt)
    print("💬 GPT 추천 결과:\n", songs)

    # 노래 목록 정리
    import re
    # GPT가 추천한 노래 목록에서 숫자(예: 1. ~, 2. ~) 제거 후, 공백과 따옴표 정리
    song_lines = [re.sub(r'^[0-9]+\.\s*', '', line).strip('" ') for line in songs.split("\n") if line.strip()]
    # 각 노래 제목에 대해 Spotify에서 검색해 트랙 URI 가져오기
    track_uris = [search_track_uri(song) for song in song_lines if song]
    # 검색 결과 중 None이 아닌 유효한 URI만 필터링
    track_uris = [uri for uri in track_uris if uri]

    # ✅ playlist_id 정의 필요!
    playlist_id = create_spotify_playlist(playlist_name)
    add_tracks_to_playlist(playlist_id, track_uris)

    print(f"✅ '{playlist_name}' 플레이리스트 생성 완료!")

    return jsonify({ # 다시 결과 QT에 전달 
        "status": "success",
        "playlist_url": f"https://open.spotify.com/playlist/{playlist_id}"
    })



if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5050)


